[package]
name = "pgbx"
version = "0.5.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg16"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16" ]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17" ]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18" ]
pg19 = ["pgrx/pg19", "pgrx-tests/pg19" ]
pg_test = []

[dependencies]
pgrx = "=0.19.3"
postgres = "0.19"
rust-s3 = { version = "0.37", default-features = false, features = ["sync-rustls-tls"] }
croner = "2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[dev-dependencies]
[dev-dependencies.pgrx-tests]
version = "=0.19.3"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
